version: "3.8"
services:
  #############################################################################################
  ###                                       FRONTEND                                        ###
  #############################################################################################
  frontend:
    tty: true
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # Binds the application folder from the host inside the container enabling hot reloading
      - ./frontend:/app
      # Ignores the node_modules of the host and uses it's own instead
      - /app/node_modules
    networks:
      - power-platform-test
    ports:
      - "8080:80"
    # We need the API to enable functionality
    depends_on:
      - api

  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  api:
    tty: true
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      # Binds the application folder from the host inside the container enabling hot reloading
      - ./api:/app
      # Ignores the node_modules of the host and uses it's own instead
      - /app/node_modules
    networks:
      - power-platform-test
    ports:
      - "3000:3000"

networks:
  power-platform-test:
    # This is what enables communication between our containers
    driver: "bridge"
