name: Deploy API

on:
  workflow_run:
    workflows:
      - Build and Upload Image
    types:
      - completed

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment: development
    steps:
      - name: Download Built Image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-upload-image.yaml
          name: api

      - name: Load Image
        run: |
          docker load -i /tmp/api.tar
          docker image ls -a

      ## TODO: Add deployment steps here
