name: Deploy API

on:
  workflow_run:
    workflows:
      - Build and Upload Image
    types:
      - completed

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment: development
    steps:
      - name: Download Built Image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-upload-image.yaml
          path: ${{ github.workspace }}
          name: api

      - name: List Files
        run: ls -al

      - name: Load Image
        run: |
          docker load -i api.tar
          docker image ls -a

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.2.0

      - name: Create Solution Zip
        id: create-zip
        run: |
          docker create --name build-container api:${{ github.event.pull_request[0].number }}
          docker start build-container
          docker exec build-container zip -r solution.zip /app/dist
          docker cp build-container:/app/solution.zip ./solution.zip
          docker stop build-container
          docker rm build-container

      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1.2.0
        with:
          solution-file: solution.zip
          environment-url: org628a9ff7.crm3.dynamics.com
          app-id: ${{ secrets.APP_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
