name: Deploy API

on:
  # Trigger on build workflow completion
  workflow_run:
    workflows:
      - Build and Upload Image
    types:
      - completed

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment: development
    steps:
      # Get the built image from the build workflow
      - name: Download Built Image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-upload-image.yaml
          path: ${{ github.workspace }}
          name: api

      # List the files in the runner's workspace
      - name: List Workspace Files
        run: ls -al

      # Load the built image tar file into the current Docker context
      - name: Load Image
        run: |
          docker load -i api.tar

      # List the images in the current Docker context
      - name: List Images
        run: |
          docker image ls -a

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Tag the image with the latest tag
      - name: Tag Image
        run: |
          docker tag api ${{ secrets.IMAGE_REPO }}/api:latest

      # Push the image to Docker Hub
      - name: Push Image
        run: |
          docker push ${{ secrets.IMAGE_REPO }}/api:latest

      # Login to Azure
      - name: Set up Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Deploy the image to Azure Web App for Containers
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: power-platform-demo
          images: ${{ secrets.IMAGE_REPO }}/api:latest
