name: Deploy API

on:
  workflow_run:
    workflows:
      - Build and Upload Image
    types:
      - completed

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment: development
    steps:
      - name: Download Built Image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-upload-image.yaml
          path: ${{ github.workspace }}
          name: api

      - name: List Workspace Files
        run: ls -al

      - name: Load Image
        run: |
          docker load -i api.tar

      - name: List Images
        run: |
          docker image ls -a

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image
        run: |
          docker tag power-platform-test_api ${{ secrets.IMAGE_REPO }}/api:latest

      - name: Push Image
        run: |
          docker push ${{ secrets.IMAGE_REPO }}/api:latest

      - name: Set up Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: power-platform-demo
          images: ${{ secrets.IMAGE_REPO }}/api:latest
