name: Build and Upload Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: docker_build
        run: |
          docker build -t api:${{ github.event.pull_request.number }} .
          docker save -o api.tar api:${{ github.event.pull_request.number }}

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api.tar
