name: Build and Upload Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: docker_build
        run: |
          cd api/
          docker build -t api .
          docker save -o ${{ github.workspace }}/api.tar api

      - name: List Workspace Directory Contents
        run: ls -la ${{ github.workspace }}

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{ github.workspace }}/api.tar
